#!/usr/bin/env python3
"""
build.py — Embeds player_data.json into mlb-analyzer.html to produce
a self-contained index.html for GitHub Pages deployment.

Usage:
  python build.py

Reads:
  - mlb-analyzer.html  (template with loadData() that checks window.PLAYER_DATA)
  - player_data.json   (generated by fetch_data.py)

Outputs:
  - index.html         (self-contained, deployable to GitHub Pages)
"""

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATE = os.path.join(SCRIPT_DIR, "mlb-analyzer.html")
DATA_FILE = os.path.join(SCRIPT_DIR, "player_data.json")
OUTPUT = os.path.join(SCRIPT_DIR, "index.html")


def main():
    # Read template
    if not os.path.exists(TEMPLATE):
        print(f"[ERROR] Template not found: {TEMPLATE}")
        sys.exit(1)

    if not os.path.exists(DATA_FILE):
        print(f"[ERROR] Data file not found: {DATA_FILE}")
        print("        Run 'python fetch_data.py' first to generate data.")
        sys.exit(1)

    with open(TEMPLATE, "r", encoding="utf-8") as f:
        html = f.read()

    with open(DATA_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Compact JSON to reduce file size (no indentation)
    data_json = json.dumps(data, separators=(",", ":"), default=str)

    # Inject the data as a script tag right before the closing </head>
    inject_script = f'<script>window.PLAYER_DATA={data_json};</script>\n</head>'
    html = html.replace("</head>", inject_script, 1)

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(html)

    size_kb = os.path.getsize(OUTPUT) / 1024
    print(f"[BUILD] Embedded {data['total_players']} players into index.html")
    print(f"        Season: {data['season']}")
    print(f"        Generated: {data['generated_at']}")
    print(f"        Output: {OUTPUT} ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
